package config

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// LLMConfig holds LLM provider configuration
type LLMConfig struct {
	Provider        string `yaml:"provider"`
	APIKey          string `yaml:"api-key,omitempty"`
	Model           string `yaml:"model"`
	BaseURL         string `yaml:"base-url,omitempty"`
	AzureDeployment string `yaml:"azure-deployment,omitempty"`
	AzureAPIVersion string `yaml:"azure-api-version,omitempty"`
	AWSRegion       string `yaml:"aws-region,omitempty"`
	EmbeddingModel  string `yaml:"embedding-model,omitempty"`
}

// CodebaseConfig holds codebase source configuration
type CodebaseConfig struct {
	Type   string `yaml:"type"`            // local | github
	Path   string `yaml:"path"`            // local path to repo
	Remote string `yaml:"remote"`          // github URL
	Token  string `yaml:"token,omitempty"` // GitHub PAT
}

// IndexConfig holds indexing configuration
type IndexConfig struct {
	Store   string    `yaml:"store"`
	LastRun time.Time `yaml:"last-run,omitempty"`
}

// DaemonConfig holds daemon configuration
type DaemonConfig struct {
	Socket string `yaml:"socket"`
	PID    string `yaml:"pid"`
	Log    string `yaml:"log"`
	JAR    string `yaml:"jar"`
}

// Timeout returns the default timeout duration for daemon operations
func (d DaemonConfig) Timeout() time.Duration {
	return time.Second
}

// DevCtxConfig is the root configuration structure
type DevCtxConfig struct {
	LLM      LLMConfig      `yaml:"llm"`
	Codebase CodebaseConfig `yaml:"codebase"`
	Index    IndexConfig    `yaml:"index"`
	Daemon   DaemonConfig   `yaml:"daemon"`
}

// Config wraps the devctx configuration
type Config struct {
	DevCtx DevCtxConfig `yaml:"devctx"`
}

// DefaultConfigDir returns the default config directory path
func DefaultConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".devctx")
}

// DefaultConfigPath returns the default config file path
func DefaultConfigPath() string {
	return filepath.Join(DefaultConfigDir(), "config.yml")
}

// NewDefaultConfig creates a new config with default values
func NewDefaultConfig() *Config {
	home, _ := os.UserHomeDir()
	devctxDir := filepath.Join(home, ".devctx")

	return &Config{
		DevCtx: DevCtxConfig{
			LLM: LLMConfig{
				Provider: "openai",
				Model:    "gpt-4o",
				BaseURL:  "https://api.openai.com/v1",
			},
			Codebase: CodebaseConfig{
				Type: "local",
			},
			Index: IndexConfig{
				Store: filepath.Join(devctxDir, "index"),
			},
			Daemon: DaemonConfig{
				Socket: filepath.Join(devctxDir, "daemon.sock"),
				PID:    filepath.Join(devctxDir, "daemon.pid"),
				Log:    filepath.Join(devctxDir, "daemon.log"),
				JAR:    filepath.Join(devctxDir, "bin", "daemon.jar"),
			},
		},
	}
}

// Load reads the config file from disk
func Load() (*Config, error) {
	return LoadFrom(DefaultConfigPath())
}

// LoadFrom reads the config file from a specific path
func LoadFrom(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config file: %w", err)
	}

	return &cfg, nil
}

// Exists checks if the config file exists
func Exists() bool {
	_, err := os.Stat(DefaultConfigPath())
	return err == nil
}

// Save writes the config to disk
func (c *Config) Save() error {
	return c.SaveTo(DefaultConfigPath())
}

// SaveTo writes the config to a specific path
func (c *Config) SaveTo(path string) error {
	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Add header comment
	header := "# ~/.devctx/config.yml\n# Auto-generated by `devctx init`. DO NOT commit this file.\n\n"
	fullData := []byte(header + string(data))

	if err := os.WriteFile(path, fullData, 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// EnsureDirectories creates all required devctx directories
func EnsureDirectories() error {
	home, _ := os.UserHomeDir()
	devctxDir := filepath.Join(home, ".devctx")

	dirs := []string{
		devctxDir,
		filepath.Join(devctxDir, "index"),
		filepath.Join(devctxDir, "index", "pgvector"),
		filepath.Join(devctxDir, "repos"),
		filepath.Join(devctxDir, "bin"),
		filepath.Join(devctxDir, "logs"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	return nil
}

// GetRepoPath returns the effective repository path
func (c *Config) GetRepoPath() string {
	if c.DevCtx.Codebase.Type == "local" {
		return c.DevCtx.Codebase.Path
	}
	return c.DevCtx.Codebase.Path // For GitHub, this is the cloned path
}

// Validate checks if the config has required fields
func (c *Config) Validate() error {
	if c.DevCtx.LLM.Provider == "" {
		return fmt.Errorf("LLM provider is required")
	}

	// API key required for cloud providers
	cloudProviders := map[string]bool{
		"openai": true, "anthropic": true, "gemini": true, "azure": true, "bedrock": true,
	}
	if cloudProviders[c.DevCtx.LLM.Provider] && c.DevCtx.LLM.APIKey == "" {
		return fmt.Errorf("API key is required for %s provider", c.DevCtx.LLM.Provider)
	}

	if c.DevCtx.Codebase.Type == "" {
		return fmt.Errorf("codebase type is required")
	}

	if c.DevCtx.Codebase.Path == "" {
		return fmt.Errorf("codebase path is required")
	}

	return nil
}
